name: gzip
description: A lightweight package for gzip compression.
version: 1.0.0
repository: https://github.com/mosuem/gzip

environment:
  sdk: ^3.9.0

dependencies:
  web: ^1.1.0

dev_dependencies:
  dart_flutter_team_lints: ^3.5.2
  test: ^1.24.0
