name: gzip
description: A lightweight package for gzip compression.
version: 0.3.0
repository: https://github.com/mosuem/gzip

environment:
  sdk: ^3.3.0

dependencies:
  web: ^1.1.0

dev_dependencies:
  dart_flutter_team_lints: ^2.1.1
  test: ^1.24.0
